version: '3'

services:
  api:
    build: ./api
    ports:
      - 3000:3000
    volumes:
      - ./api:/app
    depends_on:
      - database

  database:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
